### ISSUE TITLE
Alsa sound card and channel

### ISSUE THREAD

**Issue by pickfire** [drkh5h/slstatus#1]
Hi, I had found this project recently, I didn't know how to I check which `soundcard` and `channel` that I have, I really hope that I can make part of my `volume()` code into C.

**Comment by drkh5h** [comment]
Sorry, what?

**Comment by pickfire** [comment]
```c
/* alsa sound */
static const char soundcard[] = "PCM";
static const char channel[]   = "0";
```
How do I check which `soundcard` and `channel` I should be using, I am using an rpi2.

**Comment by drkh5h** [comment]
Oh, now I get it! :smile:

I think it should be like this on most systems:

``` c
/* alsa sound */
static const char soundcard[] = "default";
static const char channel[]   = "Master";
```

**Comment by pickfire** [comment]
Yeah, I tried that, but it didn't work. I think one of the option should be `PCM` and the other one have a different value. For mine:
```c
vol = runcmd("amixer get PCM | grep -o '[0-9]*%'");
```

**Comment by drkh5h** [comment]
I assume you only have one soundcard, thus it should be like this:

``` c
/* alsa sound */
static const char soundcard[] = "default";
static const char channel[]   = "PCM";
```

Tell me if it works with these settings! :wink:

**Comment by pickfire** [comment]
@drkh5h Thanks a lot, it works, but the number of the volume is just a bit weird (`-425%`). The `temp` is broken but I doesn't care about that. Now I am going to check how do you get the cpu and ram usage.

![2016-03-06-224913_1600x900_scrot](https://cloud.githubusercontent.com/assets/4687791/13554866/d5ea3362-e3ed-11e5-85f4-0c6643707fdb.png)

**Comment by drkh5h** [comment]
No problem @pickfire! :wink: 

But that number is very strange... Maybe it has to do with the alsa version? Which one do you use?

**Comment by pickfire** [comment]
```
> sudo pacman -Qi alsa-
alsa-firmware  (1.0.29-1)  alsa-lib  (1.1.0-1)  alsa-oss  (1.0.28-1)  alsa-plugins  (1.1.0-2)  alsa-utils  (1.1.0-1)
```

**Comment by drkh5h** [comment]
I just saw, that the PCM channel has 2 values? I think you will have to use it with Master... Just set PCM to 100% and change the volume via Master.

**Comment by pickfire** [comment]
What do you mean? Can you please show me, I don't have a lot of experience with alsa.

**Comment by drkh5h** [comment]
Ok, the PCM channel in alsa is a "sub-channel" of Master, so if you set PCM to the max (via alsamixer) you can control the volume via the Master channel. Do you get it now? :wink:

**Comment by drkh5h** [comment]
I always have the "Speaker", "Headphone" and "PCM" channels on 100% and control the volume via the "Master" channel.

**Comment by pickfire** [comment]
@drkh5h Ah, it seems like it is working now, how do you normally set the volume using command line?

**Comment by pickfire** [comment]
It seems like it drops 25% each time I lower the volume once.

**Comment by drkh5h** [comment]
@pickfire I just use the command line tool "alsamixer"

**Comment by drkh5h** [comment]
@pickfire use "+" and "-" keys instead of arrows?

**Comment by pickfire** [comment]
Okay, it seems like you have a site like I do, the cluster article looks interesting but I really hope that it can have more information.
