### ISSUE TITLE
Improve da program

### ISSUE THREAD

**Issue by wifiextender** [drkh5h/slstatus#11]
Borrow some code/idea from my program https://github.com/wifiextender/pinky-bar

**Comment by drkh5h** [comment]
sure i can. or you can do, just make a pr

**Comment by wifiextender** [comment]
I don't know what you would consider appropriate for slstatus.

```cpp
char *kernel(const char *str) {
    struct utsname KerneL;
    if (-1 == (uname(&KerneL))) {
      return smprintf("n/a");
    }
    return smprintf("%s %s", KerneL.sysname, KerneL.release);
}
```

**Comment by drkh5h** [comment]
for example this snippet looks nice! basically i would like to completely replace conky with slstatus for dwm users. so any *useful* function would be nice!

**Comment by drkh5h** [comment]
if you want you can add some useful functions in a pr

**Comment by wifiextender** [comment]
Sorry for not replying, been trying to write proper clock speed detection to show the maximum cpu clock speed in MHz regardless of the used cpu frequency governor, finally the gcc documentation gave me the necessary ingredients to do it.

---

>I would like to completely replace conky with slstatus for dwm users

I did pretty much [the same thing](https://wifiextender.github.io/#!post=openbox-to-dwm) when I started using dwm in my very first day back in february 2015.

Trying to compile the program with clang yelds some issues.

```make
CC slstatus.c
slstatus.c: In function ‘cpu_perc’:
slstatus.c:140:12: warning: conversion to ‘int’ from ‘long double’ may alter its value [-Wfloat-conversion]
     perc = 100 * ((b[0]+b[1]+b[2]) - (a[0]+a[1]+a[2])) / ((b[0]+b[1]+b[2]+b[3]) - (a[0]+a[1]+a[2]+a[3]));
            ^
slstatus.c: In function ‘disk_perc’:
slstatus.c:200:12: warning: conversion to ‘int’ from ‘float’ may alter its value [-Wfloat-conversion]
     perc = 100 * (1.0f - ((float)fs.f_bfree / (float)fs.f_blocks));
            ^
slstatus.c: In function ‘gid’:
slstatus.c:267:26: warning: comparison of unsigned expression < 0 is always false [-Wtype-limits]
     if ((gid = getgid()) < 0) {
                          ^
slstatus.c: In function ‘ram_perc’:
slstatus.c:389:12: warning: conversion to ‘int’ from ‘long int’ may alter its value [-Wconversion]
     perc = 100 * ((total - free) - (buffers + cached)) / total;
            ^
slstatus.c: At top level:
slstatus.c:615:1: warning: function declaration isn’t a prototype [-Wstrict-prototypes]
 main()
```

Stripped the warnings about unused function parameters.

**Comment by drkh5h** [comment]
Ahm, please use my Makefile, do not compile manually...

**Comment by drkh5h** [comment]
And if you want to change something make a pr, not an issue.

**Comment by wifiextender** [comment]
Oh dear, what a facepalm. And I thought that I'm talking with seasoned programmer ... cya

**Comment by drkh5h** [comment]
I have to faceapalm, not you.

**Comment by wifiextender** [comment]
>I have to faceapalm, not you.

About what ? You claim to be seasoned programmer, then how so is slstatus so badly "written", or should I say copy and paste stolen from someone else (google/stackoverflow ?) and full with bugs that you ignored from my reports earlier ?

**Comment by wifiextender** [comment]
Anyone can look at your code, your github projects and decide for themselves what "programmer" you are. You mate, are total script kiddie.

Wake up and stop proclaiming yourself "hacker" or "programmer". Get some books and start learning as of right now.

**Comment by wifiextender** [comment]
Before you say something, stop bullshitting yourself. You are not a programmer, get some books and start learning how to program in either perl, ruby or python. Spend a year or two then move to the C,C++ family.

**Comment by drkh5h** [comment]
>  You claim to be seasoned programmer, then how so is slstatus so badly "written", or should I say copy and paste stolen from someone else (google/stackoverflow ?) and full with bugs that you ignored from my reports earlier ?

What bugs? What is badly written? What is stole? What is copy-pasted? Facts please.

> Anyone can look at your code, your github projects and decide for themselves what "programmer" you are. You mate, are total script kiddie.

Tell me more. I want facts.

> Before you say something, stop bullshitting yourself. You are not a programmer, get some books and start learning how to program in either perl, ruby or python. Spend a year or two then move to the C,C++ family.

I read K&R and another C book. Before that I learned Python and HTML, CSS, some JS and PHP.

> I'm tired from leeches like you, living on other people back - botika/tdwmstatus#1 , caught the person in this link red handed stealing code from one of my projects.

What has this to do with this issue?

**Comment by wifiextender** [comment]
>What bugs ?

**-Wall** alone won't reveal them - add more flags, also scroll a few lines up and re-read my gcc and llvm reports as they point you the exact lines that need fixing.

>What is badly written

Just one of the many: you allocate memory in alsa (twice) without even some basic checks afterwards. If you ever read a C book you'll know pointers and casts in depth.

>What is copy-pasted? Facts please.

http://dwm.suckless.org/dwmstatus/, as more exotic example http://dwm.suckless.org/dwmstatus/diskspace_timechk.c 

>Anyone can look at your code, your github projects and decide for themselves what "programmer" you are. You mate, are total script kiddie.

>>Tell me more. I want facts.

This project alone is a perfect solid example that proves it all.

---

So if we are going to play this "facts" game, all you are going to say from now on will have to be proved with real facts.

Prove me that you are a real programmer, prove me that you are not a script kiddie, prove me that you are seasoned programmer - **so far all of your github projects proves otherwise**.

**Comment by phillid** [comment]
Hmm:
> seasoned

and:

> -Wstrict-prototypes

I'm not sure I follow, @wifiextender. Are you saying someone is not a seasoned programmer if they use `int foo();` rather than `int foo(void);`?

Thanks

**Comment by drkh5h** [comment]
> The -Wall flag alone won't reveal them - add more flags, also scroll a few lines up and re-read my gcc and llvm reports as they point you the exact lines that need fixing.

This are no serious bugs. They are information that can be ignored. Or should I say recommandations on coding style? I code in my own style. -Wall and -Wextra are totally enough. Also warnings can be ignored here. I tested the program with valgrind and there are no serious things anymore.

> Just one of the many: you allocate memory in alsa (twice) without even some basic checks afterwards. If you ever read a C book you'll know pointers and casts in depth.

I really have not seen this. But this does not mean my whole code is crap. It works for months now. I will fix this ASAP. Also with your fancy coding skills and as a seasoned programmer, open a PR if you are really that good.

> http://dwm.suckless.org/dwmstatus/, as more exotic example http://dwm.suckless.org/dwmstatus/diskspace_timechk.c
> 
> http://dl.suckless.org/dwm/dwm-6.1.tar.gz - the config.mk and Makefile, let's compare "your" config.mk and Makefile , did I just caught you red handed without giving dwm credits back or providing a link from where you took the code ?

I initally forked dwmstatus. It is supposed to be forked.
That diskspace function is about 5 lines of common code. Come on I programmed it with help from the manpage of statvfs. You really cannot say if i copy-pasted.
Why should I *link* them? It is under the MIT license. And they are totally ok with that. I am a suckless project member and I talked to them on IRC. It is really no issue.

> I just exposed you red handed, also this project alone is a perfect solid example that proves it all. It's hilarious how you are fighting me. I'm having so much fun arguing with such a fuck up like you that thinks "I know it all". If living life full with lies is what you get used to, then do nothing and nothing will change, you'll still have the same non-existing knowledge and produce bug ridden programs.

Really? No knowledge? I am supporting many open source projects and this is only *some* of my personal programs. Hint: I am not a full time open source programmer and I live a life away from the computer too. I am not that cellar-24/7-like-to-programmer as you.

> Prove me that you are a real programmer, prove me that you are not a script kiddie, prove me that you are seasoned programmer - so far all of your github projects proves otherwise.

Look at my dotfiles for example. They are all hand-written using man pages only.

> It tells you start from zero without copying code from the dwmstatus page or google. So you won't get caught red handed (again) by someone else.

I think you did not note that actually I did that.

> You wanted facts and I provided you the facts, and you can change what's visible - you was caught red handed without giving dwm credits back or providing a link from where you took the code, neither for "your" config.mk, nor Makefile or this "project" code. Now argue against those facts.

I am in #suckless on OFTC 24/7 via a WeeChat in tmux. I know them and they love my project. And they told me that *you* are spamming there wiki with your fucking status bar. It is *not* suckless. (autotools suck). Also dwmstatus is licensed under the MIT license. I do *not* have to link them.

> You pretend that you are programmer, that you have not copied or should I say stole code, and your project is bug-free, except you can't change what's visible and you can't change the links neither their source code in the dwm website. Even if you delete your github profile along with your forks, I have cloned them all and uploaded to another website so other people can still see what a fuck up you are.

If you find that productive and have fun doing that, feel free to do so.

**Comment by drkh5h** [comment]
Do you need help for connecting to OFTC IRC network and joining #suckless about my "copy-pasting" @wifiextender? Here you get it: http://www.irchelp.org/irchelp/irctutorial.html :laughing:

**Comment by drkh5h** [comment]
@wifiextender: https://github.com/nylira/prism-break/issues/10 I think you are the script kiddie who asks for C books in mid 2014 in this absolutely non-sense issue.

**Comment by wifiextender** [comment]
Your first comment failed to provide facts, so I am unable to comments on this subject.

You was caught red handed copying and pasting code from dwm without providing links from where you stole the code:

>http://dwm.suckless.org/dwmstatus/, as more exotic example http://dwm.suckless.org/dwmstatus/diskspace_timechk.c

>http://dl.suckless.org/dwm/dwm-6.1.tar.gz - the config.mk and Makefile, let's compare "your" config.mk and Makefile , did I just caught you red handed without giving dwm credits back or providing a link from where you took the code ?

You claimed that this project is bug-free:

>What bugs ?
>>The -Wall flag alone won't reveal them - add more flags, also scroll a few lines up and re-read my gcc and llvm reports as they point you the exact lines that need fixing.

You claimed that the project is not badly written:

>What is badly written
>>Just one of the many: you allocate memory in alsa (twice) without even some basic checks afterwards. If you ever read a C book you'll know pointers and casts in depth.

I claimed that you are total amateur:

>Anyone can look at your code, your github projects and decide for themselves what "programmer" you are. You mate, are total script kiddie.

Then you wanted facts:

>Tell me more. I want facts.
>>I just exposed you red handed, also this project alone is a perfect solid example that proves it all. It's hilarious how you are fighting me. I'm having so much fun arguing with such a fuck up like you that thinks "I know it all". If living life full with lies is what you get used to, then do nothing and nothing will change, you'll still have the same non-existing knowledge and produce bug ridden programs.

>>You wanted facts and I provided you the facts, and you can change what's visible - you was caught red handed without giving dwm credits back or providing a link from where you took the code, neither for "your" config.mk, nor Makefile or this "project" code. Now argue against those facts.

>>Never start or provoke a fight if you are not prepared for the outcome. If you did not acted so childish when I pointed you the flaws I would not come down so hard to expose what an amateur you are.

>>You pretend that you are programmer, that you have not copied or should I say stole code, and your project is bug-free, except you can't change what's visible and you can't change the links neither their source code in the dwm website. Even if you delete your github profile along with your forks, I have cloned them all and uploaded to another website so other people can still see what a fuck up you are.


>@wifiextender: nylira/prism-break#1072 I think you are the script kiddie who asks for C books in mid 2014 in this absolutely non-sense issue.

It is true. 2014 was the year I started learning C and at the beginning of 2015 I contributed 5000 changes to screenfetch-c https://github.com/woodruffw/screenfetch-c/pull/11 , https://github.com/woodruffw/screenfetch-c/pull/12, shortly after that I wrote my pinky-bar. When I don't know something I do not pretend to "know it all" and ask for help.

---


Until you provide facts I will quote myself again and again. Let's not break your "facts" game rules.

**Comment by drkh5h** [comment]
Fuck ya. I will lock this issue and use my energies for something more productive. Cya bastard.
