### ISSUE TITLE
Random crash when getting volume

### ISSUE THREAD

**Issue by joshmyzie2** [drkh5h/slstatus#12]
slstatus works great for about an hour or so, but then it will randomly crash with the following output:
```
slstatus: simple.c:283: snd_mixer_selem_get_playback_volume_range: Assertion `elem' failed.
Aborted (core dumped)
```
I've made minimal changes to config.h and nothing related to the volume lookup.
I have alsa-lib 1.1.2 installed.

**Comment by drkh5h** [comment]
I will look into it when I am back from my holidays in southern africa!

**Comment by R41z** [comment]
The code have changed now, if you don't want to wait for my pull requests to merge, I suggest you try slstatus from my repo, https://github.com/R41z/slstatus

**Comment by joshmyzie2** [comment]
Thanks.  I tried your repo, but I'm still seeing the crashes.

After tweaking my configh.h, I narrowed it down to enabling `wifi_essid`.  After disabling that, I no longer get the crashes. I'm not sure why though..

**Comment by R41z** [comment]
there is no simple.c file there :/, could you please send me the full error message you get?

**Comment by drkh5h** [comment]
I have no clue why it crashes! But I will look into it in 2,5 weeks... please send me a detailed report

**Comment by R41z** [comment]
If you could provide me with docs/manpages for function calls used there I will solve it.

**Comment by joshmyzie2** [comment]
Sorry drkh5h, please ignore this and enjoy your holidays. :)

@R41z I believe the simple.c referenced is from alsa-libs.
But I think the underlying bug is with `wifi_essid`.  It seems after it's been called too many times, something breaks.  If I have `vol_perc`, enabled it manifests itself in the error message from my initial report (those two lines are the full output).

If I disable `vol_perc` in configh.h, but keep `wifi_essid` enabled, then the bug will still manifest after about an hour, but what happens is all the `fopen` calls fail and slstatus gets stuck in infinite loop continuously retrying `fopen`.

If you want to trying reproducing, try enabling `wifi_essid` and let it run for a few hours.

**Comment by R41z** [comment]
I don't have a wifi card ^^, but I will go through the code, drkh5h have pointed some issues that need to be solved, and he mentioned something about opening files, so if I could fix both issues, that would be nice

**Comment by R41z** [comment]
this error is probably in the function vol_perc()

**Comment by drkh5h** [comment]
I will enjoy my holidays yes! :-) But strange, i use vol_perc, wifi_perc and wifi_essid daily for some time already...

**Comment by drkh5h** [comment]
But maybe thats because I use the bash endless loop from README.md?

**Comment by R41z** [comment]
the program already loops, why involved a shell functionality?

**Comment by drkh5h** [comment]
because somehow it does not run after suspend to ram for me thats because i used a shell loop around it called in xinitrc (as explained in README.md)

**Comment by drkh5h** [comment]
So I would not notice it when it exists after an hour or so as it starts again

**Comment by drkh5h** [comment]
but I will debug it when I come home by piping output to a file ;)

**Comment by R41z** [comment]
I've been having this error recently, && I've gone through the vol_perc() code and I saw two typecasts that I think are the cause of this bug, so I removed them and I ran the program for an hours without an errors, can you test my slstatus repo again? hope it's solved

**Comment by R41z** [comment]
actually.... removing these typecasts causes far more issues than before, so... I'll leave this issue for drkh5h to figure it out, sorry

**Comment by R41z** [comment]
@joshmyzie2 please test the program now, I've imported a new volume function (NOT THE ONE CLOSED THE ISSUE)

**Comment by drkh5h** [comment]
@joshmyzie2 @R41z It should work now, tested myself!

**Comment by lurekahewa** [comment]
You still need to check the return values after calling each function. Bail out if the return value is different than the expected and check again if there was allocated memory, release it and stop right there - https://gitlab.com/void0/pinky-bar (look in sound.c)

@drkhsh glad to see you changing, feel free to copy code from my project which I moved to another website.

Chipsets supporting the [cfg80211/mac80211](https://wireless.wiki.kernel.org/en/developers/documentation/nl80211) should use **libnl** as WE/WEXT is and will be no longer in development. For greater coverage and compatibility, both WE/WEXT and libnl should be supported and let the user choose which one to use.

**Comment by lurekahewa** [comment]
Avoid division by zero too:

```cpp
static char *
vol_perc(const char *card)
{
  snd_mixer_t *handle = NULL;
  snd_mixer_elem_t *elem = NULL;
  snd_mixer_selem_id_t *s_elem = NULL;
  long int vol = 0L, max = 0L, min = 0L, percent = 0L;

  if (0 != (snd_mixer_open(&handle, 0))) {
    return smprintf("%ld%%", percent);
  }

  if (0 != (snd_mixer_attach(handle, card))) {
    goto error;
  }

  if (0 != (snd_mixer_selem_register(handle, NULL, NULL))) {
    goto error;
  }

  if (0 != (snd_mixer_load(handle))) {
    goto error;
  }

  snd_mixer_selem_id_malloc(&s_elem);
  if (NULL == s_elem) {
    goto error;
  }

  snd_mixer_selem_id_set_name(s_elem, "Master");
  if (NULL == (elem = snd_mixer_find_selem(handle, s_elem))) {
    goto error;
  }

  if (0 != (snd_mixer_selem_get_playback_volume(elem, 0, &vol))) {
    goto error;
  }
  snd_mixer_selem_get_playback_volume_range(elem, &min, &max);

  percent = 0L;
  if (0 != max) {
    percent = (vol * 100) / max;
  }

error:
  if (NULL != s_elem) {
    snd_mixer_selem_id_free(s_elem);
  }
  if (NULL != handle) {
    snd_mixer_close(handle);
  }
  printf("%ld\n", percent);
  return smprintf("%ld%%", percent);

}
```

**Comment by lurekahewa** [comment]
```cpp
	long int vol, max, min;
/* signed int format specifier, cast to unsigned short from singed long
  What happens if max is 0
  3/0 ?
 */
("%d%%", ((uint_fast16_t)(vol * 100) / max));

```

```bash
/tmp/slstatus > python2
Python 2.7.10 (default, Jul  6 2016, 14:52:20) 
[GCC 4.9.3] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> 3 / 0
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ZeroDivisionError: integer division or modulo by zero
```

**Comment by drkhsh** [comment]
@lurekahewa :+1: I will implement these things ASAP. Currently I am working on porting the program to BSD, I will copy code if you are OK with that. :sunglasses: Thank you very much for your help! Great to have you on board, feel free to also open PR's / issues! I already thought pinkybar was gone and I was very sad as I wanted to steal some code :smile:

**Comment by R41z** [comment]
slow down boy! what kind of idiocy is this? you only test error on the function you will be getting data from, not the whole process, and if the last function returned error, then it's time for debugging.

Also, your code follows bad practices, I don't like that, long int vol; is the same as long vol; there is no need for longer datatype naming. your if() statements test the expected return value against the return value itself, not the other way around, can you please use the standard idioms before suggesting code? and lastly, you're using braces for single statements, this does not comply with the coding style @drkhsh follows (the suckless style), please consider removing those next time.

P.S: avoid using gotos too.

**Comment by drkhsh** [comment]
@R41z thank you for your comment, I totally agree

**Comment by R41z** [comment]
your argument about division by zero isn't 100% correct unless you prove that snd_mixer_selem_get_playback_volume_range() can give 0 in some scenarios

**Comment by R41z** [comment]
FIXED: https://github.com/R41z/slstatus/commit/fb440d8f622142c11e98e4799b7adceb33cd23b0

**Comment by lurekahewa** [comment]
@R41z I summoned @drkhsh as we know each other.

@drkhsh I use OpenBSD on daily basis and can help you out with porting the program to FreeBSD and OpenBSD, but now is the moment for either cmake or autotools decision with tests covering most of the code. You have to decide now while the code base is smaller and can be ported easily into stand alone modules for each platform.

> you only test error on the function you will be getting data from not the whole process, and if the last function returned error, then it's time for debugging.

```cpp
time t;

if (-1 == (t = time(NULL))) {
   // error handling goes here since the call to time() failed
   // any code relying on "t" will have undefined behaviour
}
```

>your if() statements test the expected return value against the function return value itself, not the other way around, can you please use the standard idioms before suggesting code

One word "right to left".

It's easy to spot the error in those short examples, in case you didn't try compiling the examples, one of the examples is perfectly valid except the unwanted variable assigning:

```cpp
#include <stdio.h>

int main(void) {
  int x = 0;

  if (x = 1) {
    printf("%s\n", "ohsnap");
  }
  return 0;
}
```

```cpp
#include <stdio.h>

int main(void) {
  int x = 0;

  if (1 = x) {
    printf("%s\n", "ohsnap");
  }
  return 0;
}
```

**Comment by R41z** [comment]
If that's your opinion, leave it for yourself, some embracing your own religion on others, if you are willing to help with contributing, follow the standard style, also, please use tabs

**Comment by R41z** [comment]
haha! your last statement is actually wrong, you used an assignment operator in the if statement, rather than using comparison operator.

**Comment by R41z** [comment]
I suggest you stick with a valid style:
http://man.openbsd.org/OpenBSD-current/man9/style.9
http://aiju.de/misc/c-style
http://suckless.org/coding_style
http://doc.cat-v.org/bell_labs/pikestyle
http://man.9front.org/6/style
http://raiz.duckdns.org/style.txt

**Comment by drkhsh** [comment]
@lurekahewa No, no auto*-hell please ok? We will port this as I started in the "port" branch.

@lurekahewa Please stick to my coding style ok?

@R41z Thanks for your commit, I will merge.
