### ISSUE TITLE
Total fuckup after about 1/2h

### ISSUE THREAD

**Issue by drkh5h** [drkh5h/slstatus#15]
After running the program for about 1/2h with the latest changes I get a total fuckup: All functions which read from files report n/a and errors... Date/time, disk, ... work normally...

Some logs:

> No protocol specified
> xcb_connection_has_error() returned true
> Failed to create secure directory (/home/drkhsh/.cache/pulse): Too many open files
> socket(): Too many open files
> xcb_connection_has_error() returned true
> shared memfd open() failed: Too many open files
> Failed to create secure directory (/home/drkhsh/.cache/pulse): Too many open files
> socket(): Too many open files
> ERROR: cannot create wakeup pipe
> ERROR: cannot create wakeup pipe
> slstatus: Could not get command output for: cmus-remote -Q 2>/dev/null | grep title | cut -d ' ' -f 3-: Too many open files
> slstatus: Could not get command output for: cmus-remote -Q 2>/dev/null | grep artist | cut -d ' ' -f 3-: Too many open files
> slstatus: Error opening battery file: /sys/class/power_supply/BAT0/charge_now: Too many open files
> slstatus: Error opening stat file: Too many open files
> slstatus: Could not open temperature file: Too many open files
> slstatus: Error opening meminfo file: Too many open files
> slstatus: error: ALSA: Too many open files
> slstatus: Could not get username: Too many open files
> slstatus: Could not open hostname file: Too many open files
> slstatus: Could not open entropy file: Too many open files
> slstatus: Error getting IP address: Too many open files
> slstatus: Error getting IP address: Too many open files
> slstatus: Error opening meminfo file: Too many open files
> slstatus: Error opening meminfo file: Too many open files

The last error messages about "Too many open files" repeat until i restart the program (it works afterwards for about 1/2h again).

**Comment by R41z** [comment]
Does Does that issue persist? if so, do you get any core dump? by reading... I think this occured in the structure, also, I just noticed that we should close the files before returning UNKNOWN_STR.

Raiz

**Comment by R41z** [comment]
I'm not sure if it's a bug or your system is shitting itself, this error message indicates EMFILE, see http://man7.org/linux/man-pages/man2/setrlimit.2.html
